# Form implementation generated from reading ui file 'd:\флешка\pet-projects\yandex_lyceum_project\app_design.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 666)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_scale = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_scale.setGeometry(QtCore.QRect(10, 80, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_scale.setFont(font)
        self.label_scale.setObjectName("label_scale")
        self.lineEdit_scale = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_scale.setGeometry(QtCore.QRect(10, 120, 541, 31))
        self.lineEdit_scale.setObjectName("lineEdit_scale")
        self.pushButton_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(290, 160, 75, 23))
        self.pushButton_search.setObjectName("pushButton_search")
        self.label_search = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_search.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_search.setFont(font)
        self.label_search.setObjectName("label_search")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_search.setGeometry(QtCore.QRect(10, 50, 621, 31))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.checkBox_topics = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_topics.setGeometry(QtCore.QRect(560, 120, 70, 31))
        self.checkBox_topics.setObjectName("checkBox_topics")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 100, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_scale.setText(_translate("MainWindow", "Введите масштаб"))
        self.pushButton_search.setText(_translate("MainWindow", "Найти"))
        self.label_search.setText(_translate("MainWindow", "Поиск"))
        self.checkBox_topics.setText(_translate("MainWindow", "Темная"))
        self.label.setText(_translate("MainWindow", "Тема карты"))
